"""Tests for Collector wiring — verifies selectors are extracted and exported correctly."""

import json
import tempfile
from pathlib import Path  # noqa: F401 — kept for potential future use

from heimdall.collector.context import ActionContext, ElementContext, StepContext
from heimdall.collector.export import Exporter


def _make_step_with_element() -> dict:
    """Build a fake step dict with one action that has element selectors."""
    element = ElementContext(
        backend_node_id=42,
        tag="BUTTON",
        attributes={"id": "login-btn", "data-testid": "submit-btn"},
        selectors={
            "css_id": "#login-btn",
            "testid": '[data-testid="submit-btn"]',
            "text": "Log in",
        },
    )
    action = ActionContext(
        action="click",
        params={"index": 3},
        success=True,
        message="Clicked element 3",
        element=element,
    )
    step = StepContext(step_number=1, instruction="Click the login button")
    step.actions.append(action)
    return step.model_dump()


def _make_step_without_element() -> dict:
    """Build a fake step dict with an action that has no element (e.g. navigate)."""
    action = ActionContext(
        action="navigate",
        params={"url": "https://example.com"},
        success=True,
        message="Navigated",
    )
    step = StepContext(step_number=2, instruction="Navigate")
    step.actions.append(action)
    return step.model_dump()


def test_export_selectors_writes_json():
    """export_selectors() should write a valid JSON file."""
    steps = [_make_step_with_element(), _make_step_without_element()]

    with tempfile.TemporaryDirectory() as tmp:
        exporter = Exporter(tmp)
        out_path = exporter.export_selectors(steps, "selectors.json")

        assert out_path.exists(), "selectors.json was not created"
        data = json.loads(out_path.read_text())
        assert isinstance(data, list)


def test_export_selectors_only_includes_elements_with_selectors():
    """export_selectors() should only include actions that have element selector data."""
    steps = [_make_step_with_element(), _make_step_without_element()]

    with tempfile.TemporaryDirectory() as tmp:
        exporter = Exporter(tmp)
        out_path = exporter.export_selectors(steps, "selectors.json")
        data = json.loads(out_path.read_text())

        # Only 1 action (the click) has element selectors
        assert len(data) == 1
        entry = data[0]
        assert entry["action"] == "click"
        assert entry["step"] == 1
        assert "css_id" in entry["selectors"]
        assert entry["selectors"]["css_id"] == "#login-btn"
        assert "testid" in entry["selectors"]
        assert entry["tag"] == "BUTTON"


def test_export_selectors_empty_steps():
    """export_selectors() on an empty step list should write an empty JSON array."""
    with tempfile.TemporaryDirectory() as tmp:
        exporter = Exporter(tmp)
        out_path = exporter.export_selectors([], "selectors.json")
        data = json.loads(out_path.read_text())
        assert data == []


def test_export_selectors_all_selector_types_preserved():
    """All selector types generated by SelectorGenerator should be preserved in export."""
    steps = [_make_step_with_element()]

    with tempfile.TemporaryDirectory() as tmp:
        exporter = Exporter(tmp)
        out_path = exporter.export_selectors(steps, "selectors.json")
        data = json.loads(out_path.read_text())

        selectors = data[0]["selectors"]
        assert selectors["css_id"] == "#login-btn"
        assert selectors["testid"] == '[data-testid="submit-btn"]'
        assert selectors["text"] == "Log in"


def test_selector_generator_href_for_anchor_tags():
    """SelectorGenerator should produce href and href_xpath for <A> tags."""
    from heimdall.dom.service import DOMNode, SelectorGenerator

    gen = SelectorGenerator()
    node = DOMNode(
        backend_node_id=99,
        node_name="A",
        attributes={
            "href": "/Logitech-Mechanical/dp/B0B39FDRKV/?th=1",
            "class": "a-link-normal",
        },
        ax_name="Logitech MX Mechanical",
    )
    selectors = gen.generate(node)

    # href selector should strip query params
    assert "href" in selectors, "href selector missing for <A> tag"
    assert "?th=1" not in selectors["href"], "Query params should be stripped from href selector"
    assert "B0B39FDRKV" in selectors["href"], "ASIN path should be in href selector"

    assert "href_xpath" in selectors, "href_xpath selector missing for <A> tag"
    assert "B0B39FDRKV" in selectors["href_xpath"]

    # Text selector should still be generated from ax_name
    assert selectors["text"] == "Logitech MX Mechanical"


def test_selector_generator_no_href_for_non_anchor():
    """SelectorGenerator should NOT produce href selectors for non-<A> tags."""
    from heimdall.dom.service import DOMNode, SelectorGenerator

    gen = SelectorGenerator()
    node = DOMNode(
        backend_node_id=100,
        node_name="BUTTON",
        attributes={"id": "submit-btn"},
        ax_name="Submit",
    )
    selectors = gen.generate(node)

    assert "href" not in selectors
    assert "href_xpath" not in selectors
    assert selectors["css_id"] == "#submit-btn"


def test_selector_generator_href_strips_query_params():
    """href selector should work cleanly even with complex query strings."""
    from heimdall.dom.service import DOMNode, SelectorGenerator

    gen = SelectorGenerator()
    node = DOMNode(
        backend_node_id=101,
        node_name="A",
        attributes={
            "href": ("/Logitech/dp/B0B39FDRKV?crid=ABC&dib=xyz&keywords=logitech+keyboard&qid=123"),
        },
        ax_name="",
    )
    selectors = gen.generate(node)

    assert "href" in selectors
    assert "?" not in selectors["href"]
    assert "/Logitech/dp/B0B39FDRKV" in selectors["href"]
